import Header from './header'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'ultimate profile website',
  description: 'Generated by create next app',
}

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' className='scrollbar-thin scrollbar-track-gray-400/20 scrollbar-thumb-[#00C6CF]/80'>
      <body className='text-gray-300 bg-white'>
          <Header/>
          admin layout.js
          {children}
      </body>
    </html>
  )
}
