import Header from './components/header'
import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'ultimate profile website',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='snap-y snap-mandatory scroll-smooth overflow-y-scroll overflow-x-hidden'>
      <body className='text-gray-300 bg-[rgb(36,36,36)]'>
        <Header/>
          {children}
      </body>
    </html>
  )
}
