import Header from './components/header'
import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-[rgb(36,36,36)] h-screen text-gray-300'>
        <Header/>
        {children}
      </body>
    </html>
  )
}
